name: Test and Serialize

on:
  push:
    branches:
      - branch-1.17

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Toolchain 1.48.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          default: true

      - name: Build
        run: cargo build --verbose
        working-directory: ./test

      - name: Run tests
        run: cargo test --verbose
        working-directory: ./test

  serialize:
    needs: [build]
    if: github.ref == 'refs/heads/branch-1.17'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: generated
          submodules: true

      - name: Install Toolchain 1.48.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          default: true

      - name: Update Submodule
        run: |
          git submodule update --remote
          cd mc-nbtdoc
          git checkout -b branch-1.17
          git pull
          cd ..
      - name: Cache Cargo Build
        uses: actions/cache@v2
        env:
          cache-name: cargo
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Serialize
        run: cargo run --bin main --release

      - name: Restore Submodule
        run: git submodule update --init 

      - name: Commit
        run: |
          git config user.name actions-user
          git config user.email action@github.com
          git add .
          git commit -m "Update to ${{ github.sha }}"
          git push
