name: Test and Generate

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: cargo build --verbose
        working-directory: ./test

      - name: Run tests
        run: cargo test --verbose
        working-directory: ./test

  generate:
    needs: [build]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: generated
          submodules: recursive

      - name: Update Submodule
        run: git submodule update --remote

      - name: Cache Cargo Build
        uses: actions/cache@v2
        env:
          cache-name: cargo
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Generate
        run: cargo run --bin main --release

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update to ${{ github.sha }}"
          git push
