name: Tick

on:
  schedule:
    - cron: '0 * * * *' # Every hour.
  workflow_dispatch: {} # Manual trigger.

jobs:
  tick:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Tick
        run: |
          chmod -R 777 .
          ./tick.py
        working-directory: ./scripts
